Completed api-registration assignment
DreSean-Sutton/c0122-code-solutions pull request #136
Opened 2022-04-05 22:44 UTC by DreSean-Sutton

![image](https://user-images.githubusercontent.com/90172283/161863072-f30a7158-f879-4a06-aaf1-7e741e6be459.png)

2022-04-05 22:55 UTC, thebearingedge requested changes

2022-04-05 22:55 UTC, thebearingedge commented on api-registration/server/index.js
> +        })
The client should receive a JSON object instead of an array. Also, they shouldn't receive the hashedPassword in the response.

2022-04-05 23:35 UTC, DreSean-Sutton commented
![image](https://user-images.githubusercontent.com/90172283/161867972-754b5237-571b-46d7-b00e-ebbeae9f1ea8.png)

2022-04-06 00:11 UTC, thebearingedge approved these changes

2022-04-06 00:15 UTC, merged