-Dre SEanean Sutton: Finished big-o-notation assignment
DreSean-Sutton/c0122-code-solutions pull request #143
Opened 2022-04-25 22:57 UTC by DreSean-Sutton

2022-04-25 23:05 UTC, thebearingedge requested changes

2022-04-25 23:05 UTC, thebearingedge commented on big-o-notation/big-o.js
> +        isUnique = false;           // 3 * n*log_2(n) = O(n*log_2(n))
Thes `n*log_2(n)` are actually O(n^2) because the search list isn't actually halving like in O(log n).

2022-04-25 23:38 UTC, thebearingedge requested changes

2022-04-25 23:38 UTC, thebearingedge commented on big-o-notation/big-o.js
> +} // Big O Notation for uniqueQuadratic: O(n*log_2(n))
👀

2022-04-26 00:34 UTC, DreSean-Sutton commented on big-o-notation/big-o.js
> +} // Big O Notation for uniqueQuadratic: O(n*log_2(n))
I forgot to save, I swear 😭

2022-04-26 01:47 UTC, thebearingedge approved these changes

2022-04-26 01:54 UTC, merged