String manipulation 2
DreSean-Sutton/c0122-code-solutions pull request #41
Opened 2022-02-04 23:39 UTC by DreSean-Sutton

![image](https://user-images.githubusercontent.com/90172283/152617295-13460f0b-f7c3-4aaa-b7da-66a57c2e4696.png)

2022-02-07 20:53 UTC, codingcodymiller requested changes

2022-02-07 20:53 UTC, codingcodymiller commented on string-manipulation-2/src/swap-chars.js
> +  var newStr = str.slice(0).split('');
Try doing this problem without converting the string to an array 🤓

2022-02-07 21:31 UTC, DreSean-Sutton commented
![image](https://user-images.githubusercontent.com/90172283/152875282-bb6078bd-b021-41b5-afef-c6804675fc75.png)

2022-02-09 16:26 UTC, thebearingedge requested changes

2022-02-09 16:26 UTC, thebearingedge commented on string-manipulation-2/src/num-vowels.js
> +        (str[i] === 'U')) {
If you lowercase your string you can check half as many comparisons.

```js
var lowerStr = str.toLowerCase();
```

2022-02-09 19:18 UTC, DreSean-Sutton commented
![image](https://user-images.githubusercontent.com/90172283/153273985-780e5f97-5c2e-473e-a213-09cfad41c961.png)

2022-02-09 19:28 UTC, thebearingedge approved these changes

2022-02-09 19:29 UTC, merged