Finished css-transitions assignment
DreSean-Sutton/c0122-code-solutions pull request #54
Opened 2022-02-10 00:52 UTC by DreSean-Sutton

![css-transitions](https://user-images.githubusercontent.com/90172283/153315887-58c0a40a-92de-4e91-b05b-62f858093c13.gif)

2022-02-10 16:28 UTC, thebearingedge requested changes

2022-02-10 16:28 UTC, thebearingedge commented on css-transitions/styles.css
> +  transition: 500ms;
Leaving out the transition property defaults to transitioning all properties, which is generally not efficient, so you should specify what to transition

```css
transition: background-color 500ms;
```

2022-02-11 17:57 UTC, DreSean-Sutton commented
![image](https://user-images.githubusercontent.com/90172283/153644030-5685711e-008f-491b-a8f0-a5040cc00f23.png)

2022-02-11 20:58 UTC, thebearingedge approved these changes

2022-02-11 21:14 UTC, merged